train = [
    ('I love this sandwich.', 'pos'),
    ('This is an amazing place!', 'pos'),
    ('I feel very good about these beers.', 'pos'),
    ('This is my best work.', 'pos'),
    ("What an awesome view", 'pos'),
    ('I do not like this restaurant', 'neg'),
    ('I am tired of this stuff.', 'neg'),
    ("I can't deal with this", 'neg'),
    ('He is my sworn enemy!', 'neg'),
    ('My boss is horrible.', 'neg')
]
test = [
    ('The beer was good.', 'pos'),
    ('I do not enjoy my job', 'neg'),
    ("I ain't feeling dandy today.", 'neg'),
    ("I feel amazing!", 'pos'),
    ('Gary is a friend of mine.', 'pos'),
    ("I can't believe I'm doing this.", 'neg')
]

train_terms = [
    ('capitol hill', 'politics'),
    ('congress', 'politics'),
    ('republican senator', 'politics'),
    ('player','sport'),
    ("mma  mixed martial arts fight" , "sport"),
    ("point", "sport"),
    ('vs.', 'business'),
    ('vs.', 'sport'),
    ("points", "sport"),
    ("race", "sport"),
    ("league", 'sport'),
    ("clubs", 'sport'),
    ("premier league", 'sport'),
    ("formula", 'sport'),
    ('rally', "sport"),
    ('motorsport', 'sport'),
    ('open', "sport"),
    ('cup,', 'sport'),
    ('coach', 'sport'),
    ('goalie', 'sport'),
    ('goalies', 'sport'),
    ("ufc", 'sport'),
    ('poker', 'sport'),
    ('set', 'sport'),
    ('transfers', 'sport'),
    ("record", 'sport'),
    ("Dow Jones industrial average", "business"),
    ("gold", "business"),
    ("hostile takeover", "business"),
    ("inflation", "buainess"),
    ("invisible hand", "business"),
    ("earnings per share", "business"),
    ("EPS", "business"),
    ("Economic growth", "business"),
    ("economies of scale", "business"),
    ("elasticity", "business"),
    ("endowment policy", "business"),
    ("enterprise value", "business"),
    ("Equity", "business"),
    ("equity derivatives", "business"),
    ("ethical investment", "business"),
    ("european bank  reconstruction development", "business"),
    ("european central bank", "business"),
    ("externalities", "business"),
    ("puck", "sport"),
    ("hockey", "sport"),
    ("soccer", "sport"),
    ("team", "sport"),
    ("ski", "sport"),
    ("skiing", "sport"),
    ("competition", "sport"),
    ("derby", "sport"),
    ("racing", "sport"),
    ("nhl", "sport"),
    ("NHL", "sport"),
    ("khl", "sport"),
    ("season", 'sport'),
    ('golf', "sport"),
    ("round", "sport"),
    ("beat", "sport"),
    ('bacteria', 'sci'),
    ('source', 'sci'),
    ("trump",  "politics"),
    ("president trump", "politics"),
    ("mr trump", "politics"),
    ("trump's trip", "politics"),
    ("putin", "politics"),
    ("minister", "politics"),
    ("dark horse", "politics"),
    ("delegate", "politics"),
    ("demagogue" , "politics"),
    ("fence mending", "politics"),
    ("filibuster", "politics"),
    ("fishing expedition", "politics"),
    ("front burner", "politics"),
    ("gerrymander", "politics"),
    ("GOP", "politics"),
    ("grass roots","politics"),
    ("ideology", "politics"),
    ("incumbent", "politics"),
    ("inside the beltway", "politics"),
    ("lame duc", "politics"),
    ("trump meets", "politics"),
    ("left-wing", "politics"),
    ("lobby" , "politics"),
    ("machine politics", "politics"),
    ("mccarthyism" , "politics"),
    ("muckraker", "politics"),
    ("nomination", "politics"),
    ("nominee", "politics"),
    ("photo-op", "politics"),
    ("platform", "politics"),
    ("debate", "politics"),
    ("vote", "politics"),
    ("political party", "politics"),
    ("political suicide", "politics"),
    ("poll", "politics"),
    ("pork barrel",  "politics"),
    ("primary", "politics"),
    ("pundit",  "politics"),
    ("reactionary", "politics"),
    ("red tape", "politics"),
    ("rubber chicken circuit", "politics"),
     ("silent majority", "politics"),
     ("slate", "politics"),
     ("smoke-filled room", "politics"),
     ("spin", "politics"),
     ("stump", "politics"),
     ("swing vote", "politics"),
     ("trial balloon", "politics"),
     ("whip", "politics"),
     ("whistle-stopping", "politics"),
     ("witch hunt", "politics"),
     ("king", "politics"),
     ("president", "politics"),
     ("minister", "politics"),
     ("feminism", "politics"),
     ("flag", "politics"),
    ("science communication","sci"),
    ("science",'sci'),
    ('nhl','sport'),
    ("trump trip texas", "politics"),
    (" Countdown to Canelo vs. Golovkin", 'sport'),
    ("feminism", "politics"),
    ("anarchism", "politics"),
    ("apolitical","politics"),
    ("aristocracy","politics"),
    ("autocracy",  "politics"),
    ("blue State", "politics"),
    ("bureaucracy", "politics"),
    ("capitalism",  "politics"),
    ("civil rights liberties", "politics"),
    ("common law",  "politics"),
    ("communism", "politics"),
    ("confederation", "politics"),
    ("conservatism", "politics"),
    ("democracy", "politics"),
    ("dictatorship", "politics"),
    ("free trade",  "politics"),
    ("left-wing", "politics"),
    ("leftist", "politics"),
    ("libertarianism", "politics"),
    ("monarchy", "politics"),
    ("monopoly",  "politics"),
    ("multi-culturism", "politics"),
    ("nation state" , "politics"),
    ("nationalism", "politics"),
    ("neo-con",  "politics"),
    ("oligarchy", "politics"),
    ("patriotism", "politics"),
    ("political correctness", "politics"),
    ("american bosses continue lobby, more quietly", "business"),
    ("samsung’s boss  sentenced prison", "business"),
    ("facebook, twitter apple get television business", 'business'),
    ("financial-market index-makers are growing", "business"),
    ("private-equity returns can be replicated with public shares", "business"),
    ("investor activism is surging in continental europe", "business"),
    ("deal", 'business'),
    ("company", "business"),
    ("money",'business' ),
    ("trade", "business"),
    ("firm", "business"),
    ("economics", 'business'),
    ("absolute advantage", 'business'),
    ("adaptive expectations", 'business'),
    ("adverse selection", 'business'),
    ("advertising", 'business'),
    ("agency costs", 'business'),
    ("agricultural policy", 'business'),
    ("agriculture", 'business'),
    ("aid" , 'business'),
    ("altruism" , 'business'),
    ("amortisation", 'business'),
    ("animal spirits", 'business'),
    ("antitrust", 'business'),
    ("appreciation", 'business'),
    ("arbitrage", 'business'),
    ("price", 'business'),
    ("wall street", 'business'),
    ("assets", 'business'),
    ("thrust", 'business'),
    ("tax", 'business'),
    ("broadcasting", "business"),
    ("business", "business"),
    ("bank", 'business'),
    ("cash", 'business'),
    ("pork-barrel politics", "politics"),
    ("propaganda", "politics"),
    ("purple state", "politics"),
    ("swing state", "politics"),
    ("red state", "politics"),
    ("republic", "politics"),
    ("right-wing", "politics"),
    ("rightist", "politics"),
    ("separation of church  state", "politics"),
    ("separation of powers", "politics"),
    ("theocracy",  "politics"),
    ("third world country", "politics"),
    ("developing nation", "politics"),
    ("totalitarianism", "politics"),
    ("welfare state", "politics"),
    ("big government", "politics"),
    ("bipartisan", "politics"),
    ("bleeding Heart", "politics"),
    ("bully pulpit",  "politics"),
    ("campaign",  "politics"),
    ("caucus", "politics"),
    ("checks  balances", "politics"),
    ("coattails", "politics"),
    ("convention", "politics"),
    ('Donald Trump is playing zero-dimensional chess', 'politics'),
    ('Trump touts Tillerson, Kelly, comments on Weinstein on way to fundraiser', 'politics'),
    ('Ken Starr  Russia indictments', 'politics'),

    ("value", 'business'),
    ("bonus", 'business'),
    ("treasury", 'business'),
    ("takeover",  'business'),
    ("stock", 'business'),
    ("share", 'business'),
    ("swaps", 'business'),
    ("index", 'business'),
    ("short selling", 'business'),
    ('Shareholder', 'business'),
    ("option", 'business'),
    ("saving account", 'business'),
    ("pound", "business"),
    ("price  earnings ratio", "business"),

    ("sport", "sport"),
    ("player", "sport"),
    ("play", "sport"),
    ("game", "sport"),
    ("match", "sport"),
    ("field", "sport"),
    ("ball", "sport"),
    ("tackle", "sport"),
    ("block", "sport"),
    ("lose", "sport"),
    ("win","sport"),
    ("infighting", "sport"),
    ("boxing", "sport"),
    ("track", "sport"),
    ("sprinter", 'sport'),
    ("goal", "sport"),
    ("score", "sport"),
    ("hat-trick", "sport"),
    ("overtime", "sport"),
    ("referee", "sport"),
    ("tie", "sport"),
    ("extra time", "sport"),
    ("injury", "sport"),
    ("tennis", "sport"),
    ("champion","sport"),
    ("champions", "sport"),
    ("point", "sport"),
    ("points", "sport"),
    ("race", "sport"),
    ("league", 'sport'),
    ("clubs", 'sport'),
    ("premier league", 'sport'),
    ("formula", 'sport'),
    ('rally', "sport"),
    ('open', "sport"),
    ('cup,', 'sport'),
    ('coach', 'sport'),
    ('goalie', 'sport'),
    ('goalies', 'sport'),
    ("ufc", 'sport'),
    ('poker', 'sport'),
    ('set', 'sport'),
    ("us open 2017: simona halep could still become world No 1 despite first round defeat  maria sharapova", 'sport'),
    ("doping", "sport"),
    ("soccer", 'sport'),
    ("hockey", 'sport'),
    ("european bank for reconstruction and development", "business"),
    ("european central bank", "business"),
    ("externalities", "business"),
    ("foul", 'sport'),
    ("politics", 'politics'),
    ("athletics", "sport"),
    ("events", "sport"),
    ("athletes", "sport"),
    ("athlete", "sport"),
    ("paavo nurmi", "sport"),
    ("carl lewis", 'sport'),
    ("triple jump", 'sport'),
    ("steeplechase", 'sport'),
    ("runner", "sport"),
    ("sprint", "sport"),
    ("starting blocks", "sport"),
    ("shot put", "sport"),
    ("relay", 'sport'),
    ("pole-vault", 'sport'),
    ("marathon", "sport"),
    ("long jump", "sport"),
    ("lap", "sport"),
    ("javelin", "sport"),
    ("high jump", "sport"),
    ('jumping', "sport"),
    ("hurdles", 'sport'),
    ("heptathlon", 'sport'),
    ("hammer", 'sport'),
    ("discus", "sport"),
    ("decathlon", 'sport'),
    ("bell lap", "sport"),
    ('baton', 'sport'),
    ('badminton', 'sport'),
    ('basketball', 'sport'),
    ('football', 'sport'),
    ('gymnastics', 'sport'),
    ('rugby', 'sport'),
    ('swimming', 'sport'),
    ('olympic', 'sport'),
    ("sport", "sport"),
    ('figure skating', 'sport'),
    ("", "sport"),
    ('skiing', 'sport'),
    ("baseball", "sport"),
    ('cricket', 'sport'),
    ("squash", "sport"),
    ('court', 'sport'),
    ("ace", "sport"),
    ('serve', 'sport'),
    ("rearcourt", "sport"),
    ('racket', 'sport'),
    ("court", "sport"),
    ('net', 'sport'),
    ("forecourt", "sport"),
    ('drive', 'sport'),
    ("let", "sport"),
    ('shot', 'sport'),
    ("doubles", "sport"),
    ('clear', 'sport'),
    ("bird  birdie", "sport"),
    ('baseline', 'sport'),
    ("backhand", "sport"),
    ('pass', 'sport'),
    ("passing", "sport"),
    ('smash', 'sport'),
    ("michael jordan", "sport"),
    ('assist', 'sport'),
    ("basket", "sport"),
    ('bounce', 'sport'),
    ("draft", "sport"),
    ('double-dribbling', 'sport'),
    ("free throw", "sport"),
    ('kick', 'sport'),
    ("possession", "sport"),
    ('substitute', 'sport'),
    ("three-point line", "sport"),
    ('time-out', 'sport'),
    ("travelling", "sport"),
    ('turnover', 'sport'),
    ("violation", "sport"),
    ('penalty', 'sport'),
    ("muhammad ali", "sport"),
    ('bare-knuckled', 'sport'),
    ("blow", "sport"),
    ('clinch', 'sport'),
    ("bout", "sport"),
    ("combination", "sport"),
    ("counterpunch", "sport"),
    ("cross", "sport"),
    ("gloves  boxing ", "sport"),
    ("holding", "sport"),
    ("hook", "sport"),
    ("jab", "sport"),
    ("knockdown", "sport"),
    ("punch", "sport"),
    ("knockout", "sport"),
    ("blow", "sport"),
    ("promoter", "sport"),
    ("manager", "sport"),
    ("tko", "sport"),
    ("unanimous decision", "sport"),
    ("weigh-in", "sport"),
    ("upper cut", "sport"),
    ("weight classes", "sport"),
    ("split decision", "sport"),
    ("southpaw", "sport"),
    ("rounds", "sport"),
    ("ropes", "sport"),
    ("ring", "sport"),
    ("defender", "sport"),
    ("draw", "sport"),
    ("handball", "sport"),
    ("offside", "sport"),
    ("shootout", "sport"),
    ("pitch", "sport"),


    ("mars", "sci"),
    ('planet', 'sci'),
    ("space", "sci"),
    ("moon", "sci"),
    ("moon landing", 'sci'),
    ('aberration', 'sci'),
    ('absolute zero', 'sci'),
    ('absorption', 'sci'),
    ('abundance', 'sci'),
    ('accelerometer', 'sci'),
    ('accretion', 'sci'),
    ('active galactic nucleus agn', 'sci'),
    ('active galaxy', 'sci'),
    ('aeronomy', 'sci'),
    ('aerosol', 'sci'),
    ('aerosol collector', 'sci'),
    ('algol', 'sci'), ('alignment', 'sci'),
    ('altitude', 'sci'),
    ('angstrom', 'sci'),
    ('anisotropy inhomogeneity', 'sci'),
    ('cosmic', 'sci'),
    ('microwave background', 'sci'),
    ('antenna', 'sci'), ('gain', 'sci'),
    ('antimatter', 'sci'),
    ('aperture', 'sci'),
    ('aphelion', 'sci'),
    ('apocentre', 'sci'),
    ('apogee', 'sci'),
    ('arcmin', 'sci'),
    ('arcsec', 'sci'),
    ('argon', 'sci'),
    ('scientific evidence', 'sci'),
    ('altitude', 'sci'),
    ('angstrom', 'sci'),
    ('anisotropy, inhomogeneity', 'sci'),
    ('cosmic', 'sci'),
    ('microwave background', 'sci'),
    ('antenna', 'sci'),
    ('gain', 'sci'),
    ('antimatter', 'sci'),
    ('scientific', 'sci'),
    ('aperture', 'sci'),
    ('aphelion', 'sci'),
    ('apocentre', 'sci'),
    ('apogee', 'sci'),
    ('arcmin', 'sci'),
    ('arcsec', 'sci'),
    ('country','politics'),
    ('argon', 'sci'),
    ('ariane rockets', 'sci'),
    ('asteroid', 'sci'),
    ('asteroid belt', 'sci'),
    ('astigmatism', 'sci'),
    ('astrometry', 'sci'),
    ('attitude', 'sci'),
    ('astronomical unit au', 'sci'),
    ('astronomy', 'sci'),
    ('cyborg', 'sci'),
    ('computer', 'sci'),
    ('solar', 'sci'),
    ('astrophysics', 'sci'),
    ('atmosphere', 'sci'),
    ('aurora', 'sci'),
    ('baffle', 'sci'),
    ('baryons', 'sci'),
    ('bepicolombo mission', 'sci'),
    ('bepposax satellite', 'sci'),
     ('big bang', 'sci'),
     ('big crunch', 'sci'),
    ('billion', 'sci'),
     ('binary star', 'sci'),
     ('black hole', 'sci'),
     ('blazar', 'sci'),
     ('blueshift', 'sci'),
     ('bolometer', 'sci'),
     ('bremsstrahlung', 'sci'),
    ('brown dwarf', 'sci'),
    ('capture orbit', 'sci'),
    ('carbonaceous compounds', 'sci'),
    ('cassegrain telescope', 'sci'),
    ('cassini division', 'sci'),
    ('cassini-huygens mission', 'sci'),
    ('cataclysmic variable', 'sci'),
    ('celsius', 'sci'), ('centaur rocket', 'sci'),
    ('cepheid variable', 'sci'), ('charged particles', 'sci'),
    ('checkout', 'sci'),
    ('chromosphere', 'sci'),
    ('climatology', 'sci'),
    ('closed universe', 'sci'),
    ('cluster mission', 'sci'),
    ('cosmic microwave background radiation', 'sci'),
    ('coast phase', 'sci'),
    ('coded mask', 'sci'),
    ('cold dark matter', 'sci'),
    ('coma', 'sci'),
    ('comet', 'sci'),
    ('compton scattering  inverse compton scattering', 'sci'),
    ('concave', 'sci'),
    ('conductivity thermal', 'sci'),
    ('convection', 'sci'),
    ('convection model', 'sci'),
    ('convex', 'sci'),
    ('core', 'sci'),
    ('cornerstone', 'sci'),
    ('corona', 'sci'),
    ('coronal mass ejection cme', 'sci'),
    ('coronagraph', 'sci'),
    ('cosmic background explorer cobe satellite', 'sci'),
    ('cosmic rays', 'sci'),
    ('cosmology', 'sci'),
    ('crater', 'sci'),
    ('critical density', 'sci'),
    ('cruise phase', 'sci'),
    ('crust', 'sci'),
    ('cryostat', 'sci'),
    ('cygnus x-1', 'sci'),
     ('cygnus x-3', 'sci'),
    ('dark matter', 'sci'),
    ('darwin mission', 'sci'),
    ('data', 'sci'),
    ('decaying orbit', 'sci'),
    ('deep space network', 'sci'),
    ('dsn', 'sci'),
    ('density', 'sci'),
    ('descent phase', 'sci'),
    ('differential rotation', 'sci'),
    ('diffraction grating', 'sci'),
    ('diffuse x-ray background', 'sci'),
    ('diode', 'sci'),
    ('dispersion', 'sci'),
    ('doppler shift', 'sci'),
    ('drag', 'sci'),
    ('dust', 'sci'),
    ('cosmic', 'sci'),
    ('interstellar', 'sci'),
    ('earth', 'sci'),
    ('eclipse', 'sci'),
    ('solar', 'sci'),
    ('eclipse, lunar', 'sci'),
    ('ecliptic plane', 'sci'),
    ('effective area', 'sci'),
    ('einstein cosmological constant', 'sci'),
    ('lambda', 'sci'),
    ('electric propulsion', 'sci'),
    ('electromagnetic radiation', 'sci'),
    ('electromagnetic spectrum', 'sci'),
    ('electron', 'sci'),
    ('electron-positron annihilation', 'sci'),
    ('electronvolt', 'sci'),
    ('ev', 'sci'),
    ('element', 'sci'),
    ('elliptical orbit', 'sci'),
    ('emission', 'sci'),
    ('energy', 'sci'),
    ('european space agency', 'sci'),
    ('esa)', 'sci'),
    ('escape velocity', 'sci'),
    ('ethane', 'sci'),
    ('exobiology', 'sci'),
    ('exosat satellite', 'sci'),
    ('extinction', 'sci'),
    ('extragalactic', 'sci'),
    ('extravehicular', 'sci'),
    ('extreme ultraviolet euv', 'sci'),
    ('facula', 'sci'),
    ('fahrenheit', 'sci'),
    ('field of view', 'sci'),
    ('fov', 'sci'),
    ('filament', 'sci'),
    ('filter', 'sci'),
    ('first mission', 'sci'),
    ('flat universe', 'sci'),
    ('fluctuations( cosmic microwave background', 'sci'),
    ('fly-by', 'sci'),
    ('focal plane', 'sci'),
    ('focus', 'sci'),
    ('french guiana', 'sci'),
    ('frequency', 'sci'),
    ('fusion', 'sci'),
    ('gaia mission', 'sci'),
    ('galaxy', 'sci'),
    ('galaxy clusters', 'sci'),
    ('gamma ray', 'sci'),
    ('gamma-ray astronomy', 'sci'),
    ('gamma-ray burst', 'sci'),
    ('grb', 'sci'),
    ('ganymede', 'sci'),
    ('general relativity', 'sci'),
    ('germanium detector', 'sci'),
    ('giotto mission', 'sci'),
    ('granulation', 'sci'),
    ('grating transmission reflection', 'sci'),
    ('gravitational arc lens', 'sci'),
    ('gravitational field', 'sci'),
    ('gravitational wave', 'sci'),
    ('gravity', 'sci'),
    ('gravity assist', 'sci'),
    ('grazing incidence', 'sci'),
    ('grigg-skjellerup comet', 'sci'),
    ('ground segment', 'sci'),
    ('guaranteed time', 'sci'),
    ('gyroscope', 'sci'),
    ('hale-bopp', 'sci'),
    ('halley comet', 'sci'),
    ('half-energy width', 'sci'),
    ('heat capacity', 'sci'),
    ('heat shield', 'sci'),
    ('heliocentric', 'sci'),
    ('helioseismology', 'sci'),
    ('heliosphere', 'sci'),
    ('herschel mission', 'sci'),
    ('hertz hz', 'sci'),
    ('hertzsprung-russell hr diagram', 'sci'),
    ('hipparcos mission', 'sci'),
    ('hubble constant', 'sci'),
    ('hubble law', 'sci'),
    ('hubble space telescope hst mission', 'sci'),
    ('huygens mission', 'sci'),
    ('hydrazine', 'sci'),
    ('hydrocarbons', 'sci'),
    ('hyperbolic', 'sci'),
    ('igneous rock', 'sci'),
    ('illuminated', 'sci'),
    ('image', 'sci'),
    ('imager', 'sci'),
    ('imaging', 'sci'),
    ('impact crater', 'sci'),
    ('inclination angle', 'sci'),
    ('inflationary universe', 'sci'),
    ('infrared astronomical satellite iras', 'sci'),
    ('infrared light', 'sci'),
    ('infrared space observatory iso mission', 'sci'),
    ('injection (into orbit)', 'sci'),
    ('instrument', 'sci'),
    ('integral mission', 'sci'),
    ('integration satellite instrument', 'sci'),
    ('interferometer', 'sci'),
    ('interferometry', 'sci'),
    ('international ultraviolet explorer iue emission', 'sci'),
    ('interplanetary voyage', 'sci'),
    ('interstellar', 'sci'),
    ('ion', 'sci'),
    ('isotope', 'sci'),
    ('isotropy', 'sci'),
    ('jupiter', 'sci'),
    ('k-band', 'sci'),
    ('kelvin', 'sci'),
    ('kourou', 'sci'),
    ("fight", 'sport'),
    ("promote",'sport'),
    ('i voted', 'politics'),
    ('vote', 'politics'),
    ("signal", "sci"),
    ('boxer', 'sport'),
    ('espn', 'sport'),
    ('nba', 'sport'),
    ("nfl", 'sport'),
    ('mlb', 'sport'),
    ("gas", 'sci' ),
    ('gas ball', 'sci'),

     ('kuiper belt', 'sci'),
    ('lagrangian points', 'sci'),
    ('lander', 'sci'),
    ('latch', 'sci'),
    ('launch window', 'sci'),
    ('launcher', 'sci'),
    ('lens', 'sci'), ('leonids', 'sci'),
    ('light', 'sci'),
    ('light elements', 'sci'),
    ('lightning', 'sci'),
    ('light-year ly', 'sci'),
    ('line absorption', 'sci'),
    ('luminosity', 'sci'),
    ('mach number', 'sci'),
    ('magnetic field', 'sci'),
    ('magnetic force', 'sci'),
    ('magnetometer', 'sci'),
    ('magnetopause', 'sci'),
    ('magnetosphere', 'sci'),
    ('magnitude absolute', 'sci'),
    ('magnitude apparent', 'sci'),
    ('main sequence', 'sci'),
    ('mandrel', 'sci'),
    ('mantle', 'sci'),
    ('manufacturing', 'sci'),
    ('mars', 'sci'),
    ('mars express mission', 'sci'),
    ('mass', 'sci'),
    ('matter', 'sci'),
    ('measurements in-situ', 'sci'),
    ('measurements remote', 'sci'),
    ('mercury', 'sci'),
    ('meteor', 'sci'),
    ('meteor shower', 'sci'),
    ('meteorite', 'sci'),
    ('meteoroid', 'sci'),
    ('methane', 'sci'),
    ('microgravity', 'sci'),
    ('micron', 'sci'),
    ('microwave', 'sci'),

    ('milky way', 'sci'),
    ('mirror', 'sci'),
    ('module satellite', 'sci'),
    ('molecular cloud', 'sci'),
    ('monitor', 'sci'),
    ('moon', 'sci'),
    ('multimirror', 'sci'),
    ('multi-wavelength (observations)', 'sci'),
    ('near-earth asteroid', 'sci'),
    ('nebula', 'sci'),
    ('neptune', 'sci'),
    ('neutrino', 'sci'),
    ('neutron', 'sci'),
    ('nitrogen', 'sci'),
    ('non-baryonic matter', 'sci'),
    ('nova', 'sci'),
    ('nuclear fusion', 'sci'),
    ('nucleosynthesis', 'sci'),
    ('nucleus', 'sci'),
    ('occultation', 'sci'),
    ('oort cloud', 'sci'),
    ('open universe', 'sci'),
    ('opposition', 'sci'),
    ('optical light', 'sci'),
    ('visible light', 'sci'),
    ('optics', 'sci'),
    ('orbit', 'sci'),
    ('orbit acquisition', 'sci'),
    ('orbiter', 'sci'),
    ('organics', 'sci'),
    ('orientation', 'sci'),
    ('ozone layer', 'sci'),
    ('parabolic (mirror)', 'sci'),
    ('parallax', 'sci'),
    ('parsec', 'sci'),
    ('particle', 'sci'),
    ('payload', 'sci'),
    ('payload module', 'sci'),
    ('periapsis', 'sci'),
    ('pericentre', 'sci'),
    ('perigee', 'sci'),
    ('perihelic opposition', 'sci'),
    ('perihelion', 'sci'),
    ('period', 'sci'),
    ('photochemistry', 'sci'),
    ('photometer', 'sci'),
    ('photon', 'sci'),
    ('picture', 'sci'),
    ('pipe-line processing', 'sci'),
    ('pixel', 'sci'),
    ('planck constant', 'sci'),
    ("planck's law", 'sci'),
    ('planck mission', 'sci'),
    ('plane (focal)', 'sci'),
    ('planet', 'sci'),
    ('planetary nebula', 'sci'),
    ('plasma', 'sci'),
    ('platform', 'sci'),
    ('pleiades', 'sci'),
    ('plumes', 'sci'),
    ('pluto', 'sci'),
    ('pole', 'sci'),
    ('polarisation', 'sci'),
    ('positron', 'sci'),
    ('prebiotic', 'sci'),
    ('preliminary design review', 'sci'),
    ('primaeval soup', 'sci'),
    ('primary mirror', 'sci'),
    ('primordial nucleosynthesis', 'sci'),
    ('prism', 'sci'), ('probe', 'sci'),
    ('prominence (solar)', 'sci'),
    ('proportional counter', 'sci'),
    ('propulsion', 'sci'),
    ('proton', 'sci'),
    ('protoplanetary disc', 'sci'),
    ('protostellar object', 'sci'),
    ('pulsar', 'sci'),
    ('pyrolyser', 'sci'),
    ('qualification model', 'sci'),
    ('quantum', 'sci'),
    ('theory mechanics', 'sci'),
    ('quark', 'sci'),
    ('quasar', 'sci'),
    ('quick-look analysis', 'sci'),
    ('radiation', 'sci'),
    ('radiation belt van allen', 'sci'),
    ('radio waves', 'sci'),
    ('radioactivity', 'sci'),
    ('reboost', 'sci'),
    ('recombination era', 'sci'),
    ('red giant', 'sci'),
    ('redshift', 'sci'),
    ('reduction', 'sci'),
    ('reflecting telescope', 'sci'),
    ('reflector', 'sci'),
    ('refracting telescope', 'sci'),
    ('replication', 'sci'),
    ('resolution (angular, spectral)', 'sci'),
    ('retrograde', 'sci'),
    ('revolution', 'sci'),
    ("rings saturn's", 'sci'),
    ('ritchey-chretien', 'sci'),
    ('robot', 'sci'),
    ('roche limit', 'sci'),
    ('rocket', 'sci'),
    ('rosat satellite', 'sci'),
    ('rosetta mission', 'sci'),
    ('rotation', 'sci'),
    ('rover', 'sci'),
    ('s-band', 'sci'),
    ('sagittarius', 'sci'),
    ('satellite', 'sci'),
    ('saturn', 'sci'),
    ('secondary mirror', 'sci'),
    ('sedimentary rock', 'sci'),
    ('separation satellite', 'sci'),
    ('serendipity', 'sci'),
    ('service module', 'sci'),
    ('servicing mission', 'sci'),
    ('seyfert galaxy', 'sci'),
    ('shell', 'sci'),
    ('shoemaker-levy 9 comet', 'sci'),
    ('smart-1 mission', 'sci'),
    ('solar heliospheric observatory soho mission', 'sci'),
    ('solar array', 'sci'), ('solar flare', 'sci'),
    ('solar storm', 'sci'),
    ('solar system', 'sci'),
    ('solar wind', 'sci'),
    ('source', 'sci'), ('soyuz -fregat rocket', 'sci'),
    ('spacecraft', 'sci'),
    ('space infrared telescope facility', 'sci'),
    ('sirtf', 'sci'),
    ('space weather', 'sci'),
    ('spectral class star', 'sci'),
    ('spectral lines', 'sci'),
    ('spectrophotometers', 'sci'),
    ('spectrograph', 'sci'),
    ('spectrometer', 'sci'),
    ('spectrometer  mossbauer', 'sci'),
    ('spectrometer mass', 'sci'),
    ('spectroscopy', 'sci'),
    ('spectrum', 'sci'),
    ('spherical aberration', 'sci'),
    ('stability', 'sci'),
    ('satellite', 'sci'),
    ('star', 'sci'),
    ('starburst', 'sci'),
    ('galaxies', 'sci'),
    ('stratospheric observatory for infrared astronomy sofia', 'sci'),
    ('structural and thermal model', 'sci'),
    ('sublimation', 'sci'), ('submillimetre', 'sci'),
    ('sub-mm', 'sci'),
    ('sun', 'sci'),
    ('sunspot', 'sci'),
    ('sunspot cycle', 'sci'),
    ('supernova', 'sci'), ('synchrotron radiation', 'sci'),
    ('systems engineering review', 'sci'),
    ('swing-by', 'sci'),
    ('telemetry', 'sci'),
    ('telescope', 'sci'),
    ('telescope wolter', 'sci'),
    ('temperature', 'sci'),
    ('terrestrial planets', 'sci'),
    ('testing', 'sci'),
    ('spacecraft', 'sci'),
    ('thermal gradient', 'sci'),
    ('thrusters', 'sci'),
    ('titan', 'sci'),
    ('tracking', 'sci'),
    ('tube', 'sci'),
    ('uhuru satellite', 'sci'),
    ('ultra luminous infrared galaxies (ulirg)', 'sci'),
    ('ultraviolet light', 'sci'),
    ('ulysses mission', 'sci'),
    ('universe', 'sci'), ('uranus', 'sci'),
    ('van allen', 'sci'),
    ('van allen radiation belt', 'sci'),
    ('vacuum', 'sci'),
    ('venus', 'sci'),
    ('visibility', 'sci'),
    ('volt', 'sci'),

    ('watt', 'sci'),
    ('wavelength', 'sci'),
    ('white dwarf', 'sci'),
    ('wirtanen-comet', 'sci'),
    ('x-band', 'sci'),
    ('xeus mission', 'sci'),
    ('xmm-newton', 'sci'),
    ('multi-mirror', 'sci'),
    ('x-ray', 'sci'),
    ('zonal wind', 'sci'),



    ('accounts payable (ap)', 'business'),
    ('accounts receivable ar', 'business'),
    ('accrual based accounting', 'business'),
    ('accumulated depreciation', 'business'),
    ('acid test', 'business'),
    ('acquisition costs', 'business'),
    ('adaptive firm', 'business'),
    ('adventure capital', 'business'),
    ('advertising opportunity', 'business'),
    ('agent', 'business'),
    ('asset turnover', 'business'),
    ('assets', 'business'),
    ('back end', 'business'),
    ('benchmark', 'business'),
    ('brand', 'business'),
    ('brand equity', 'business'),
    ('brand extension strategy', 'business'),
    ('brand recognition', 'business'),
    ('break-even analysis', 'business'),
    ('break-even point', 'business'),
    ('broker', 'business'),
    ('bundling', 'business'),
    ('burden rate', 'business'),
    ('business mission', 'business'),
    ('business plan', 'business'),
    ('buy-sell agreement', 'business'),
    ('c corporation', 'business'),
    ('(c corp)', 'business'),
    ('compound average growth rate', 'business'),
    ('(cagr)', 'business'),
    ('cannibalization', 'business'),
    ('capital assets', 'business'),
    ('capital expenditure', 'business'),
    ('capital input', 'business'),
    ('cash', 'business'),
    ('cash basis', 'business'),
    ('cash flow', 'business'),
    ('cash flow budget', 'business'),
    ('cash flow statement', 'business'),
    ('cash sales', 'business'),
    ('cash spending', 'business'),
    ('central driving forces model', 'business'),
    ('channel conflicts', 'business'),
    ('channels of distribution', 'business'),
    ('click-through rate', 'business'),
    ('co-branding', 'business'),
    ('cost of goods sold', 'business'),
    ('(cogs)', 'business'),
    ('collection days', 'business'),
    ('collection period (days)', 'business'),
    ('commission', 'business'),
    ('commissions percent', 'business'),
    ('community interest company', 'business'),
    ('(cic)', 'business'), ('competitive advantage', 'business'),
    ('competitive analysis', 'business'),
    ('competitive entry wedges', 'business'),
    ('completed store transactions', 'business'),
    ('concentrated target marketing', 'business'),
    ('contribution', 'business'),
    ('contribution margin', 'business'),
    ('conversion rate', 'business'),
    ('core marketing strategy', 'business'),
    ('corporation', 'business'),
    ('corridor principal', 'business'),
    ('cost of sales', 'business'),
    ('cross elasticity of demand', 'business'),
    ('current assets', 'business'),
    ('current debt', 'business'),
    ('current liabilities', 'business'),
    ('doing business as', 'business'),
    ('dba', 'business'),
    ('debt equity', 'business'),
    ('depreciation', 'business'),
    ('differentiated target marketing', 'business'),
    ('differentiation', 'business'),
    ('direct cost of sales', 'business'),
    ('directory', 'business'),
    ('distinctive competency', 'business'),
    ('diversification', 'business'),
    ('dividends', 'business'),
    ('dual distribution', 'business'),
    ('early adopters', 'business'),
    ('early majority', 'business'),
    ('earnings', 'business'),
    ("demand", 'business'),
    ('ebit', 'business'),
    ('ebitda', 'business'),
    ('(eih)', 'business'),
    ('entrepreneur', 'business'),
    ('equity', 'business'),
    ('everett rogers', 'business'),
    ('distribution', 'business'),
     ('expense', 'business'),
    ('experience curve', 'business'),
    ('features, advantages,  benifits', 'business'),

    ('fab', 'business'), ('failure rule, common causes', 'business'),
    ('failure rule, exceptions to the rule', 'business'),
    ('fatal 2% rule', 'business'),
    ('first mover', 'business'),
    ('first mover advantage', 'business'),
    ('fiscal', 'business'),
    ('five forces model', 'business'),
    ('focus group', 'business'),
    ('goodwill', 'business'),
    ('harvesting', 'business'),
    ('ideas vs opportunities', 'business'),
    ('impressions', 'business'),
    ('(ipo)', 'business'),
    ('innovators', 'business'),
    ('intraprenuership', 'business'),
    ('inventory', 'business'),
    ('jobber', 'business'),
    ('labor', 'business'),
    ('laggards', 'business'),
    ('buy out', 'business'),
    ('lbo', 'business'),
    ('leveraged', 'business'),
    ('liabilities', 'business'),
    ('life cycle', 'business'),
    ('(llc)', 'business'),
      ('loss', 'business'),
    ('loyalty programs', 'business'),
    ('manufacturer’s agent', 'business'),
    ('marketing', 'business'),
    ('materials', 'business'),
    ('mission statement', 'business'),
    ('npv', 'business'),
    ('net worth', 'business'),
    ('new visitors', 'business'),
    ('newsletter subscriptions', 'business'),
    ('invented', 'business'),
    ('(nih)', 'business'),
    ('obligation', 'business'),
    ('obligations', 'business'),
    ('offering', 'business'),
    ('on-costs', 'business'),
    ('leverage', 'business'),
    ('expenses', 'business'),
    ('operations control', 'business'),
    ('opportunities ideas', 'business'),
    ('opportunity analysis', 'business'),
    ('oem', 'business'),
    ('other short-term liabilities', 'business'),
    ('outsourcing', 'business'),
    ('page views', 'business'),
    ('partnership', 'business'),
    ('payables', 'business'),
    ('payback period', 'business'),
    ('payment ', 'business'),
    ('payroll', 'business'),
    ('perceived risk', 'business'),
    ('perceptual map', 'business'),
    ('pest analysis', 'business'),
    ('plat', 'business'),
    ('equipment', 'business'),
    ('(pop)', 'business'),
    ('portfolio', 'business'),
    ('positioning', 'business'),
    ('premiums', 'business'),
    ('income statement', 'business'),
    ('privately owned', 'business'),
    ('pro forma statements', 'business'),
    ('product', 'business'),
    ('development', 'business'),
    ('plc', 'business'),
    ('product line', 'business'),
    ('profit', 'business'),
      ('public relations', 'business'),
    ('publicly traded', 'business'),
    ('pull communication strategy', 'business'),
    ('push communication strategy', 'business'),
    ('receivables', 'business'),
    ('repositioning', 'business'),
    ('resource requirements', 'business'),
    ('retained earnings', 'business'),
    ('(roi)', 'business'),
    ('rich-gumpert evaluation system', 'business'),
    ('s corporation', 'business'),
    ('(s corp)', 'business'),
    ('credit', 'business'),
    ('sales forecast', 'business'),
    ('scrambled merchandising', 'business'),
    ('senior corps of retired executives score', 'business'),
    ('shareholders', 'business'),
    ('short-term', 'business'),
    ('short-term assets', 'business'),
    ('short-term notes', 'business'),
    ('short-term liabilities', 'business'),
    ('simple linear regression', 'business'),
    ('situation analysis', 'business'),
    ('slotting allowances', 'business'),
    ('sbic', 'business'),
    ('sole proprietorship', 'business'),
    ('sole trader', 'business'),
    ('starting date', 'business'),
    ('strategic control', 'business'),
    ('strategic marketing management', 'business'),
    ('success factors', 'business'),
    ('success requirements', 'business'),
    ('surplus or deficit', 'business'),
    ('sunk cost', 'business'),
    ('switching costs', 'business'),
     ('swot analysis', 'business'),
    ('systematic innovation', 'business'),
    ('tactics', 'business'),
    ('target market', 'business'),
    ('target marketing', 'business'),
    ('tax rate percent', 'business'),
    ('taxes incurred', 'business'),
    ('telemarketing', 'business'),
    ('trade margin', 'business'),
    ('trading down', 'business'),
    ('trading up', 'business'),
    ('traffic', 'business'),
    ('types of entrepreneurs', 'business'),
    ('user interface', 'business'),
    ('(ui)', 'business'),
    ('unique user sessions', 'business'),
    ('unit variable cost', 'business'),
    ('units break-even', 'business'),
    ('unpaid expenses', 'business'),
    ('user benefits', 'business'),
    ('user registration', 'business'),
    ('valuation', 'business'),
    ('value', 'business'),
    ('variable cost', 'business'),
    ('variance', 'business'),
    ('venture capitalists', 'business'),
    ('(vc)', 'business'),
    ('venture capital', 'business'),
    ('website', 'business'),
    ('website metrics', 'business'),
    ('website traffic', 'business'),
    ('wholesaler', 'business'),
    ("fighter", 'sport'),
    ("china", 'politics'),
    ("korea", 'politics'),
  #  ('leukemia', 'medical'),
   # ('medical', 'medical'),
   # ('blood', 'medical'),
   # ('ill', 'medical'),
   # ('cell', 'medical'),
   # ('scan', 'medical'),
    #('body', 'medical'),

    #('pain', 'medical'),
    #('health', 'medical'),
    #('fitness', 'medical'),
    #('medicine', 'medical'),
    #('drug', 'medical'),
    #('cure', 'medical'),
    #('disease', 'medical'),
    #('illness', 'medical'),
    #('condition', 'medical'),
    #('cancer', 'medical'),
    ("donald trump", 'politics'),
    ("Trump", "politics"),
    ('Obama', "politics"),
    ("president trump", "politics"),
    ("mr Trump", "politics"),
    ("Trump's trip", "politics"),
    ("putin", "politics"),
    ("minister", "politics"),
    ('summit meeting', 'politics'),
    ('NATO', 'politics'),
    ('Embassy', 'politics'),
    ('embassy', 'politics'),
    ('trump to attend NATO meeting in May, White House says','politics'),
    ('tillerson, Kelly, comments Weinstein fundraiser', 'politics'),
    ('british prime minister', 'politics'),
    ('democrats', 'politics'),
    ('rally', 'politics'),
    ('independence', 'politics'),
    #("un", 'politics'),
    #("usa", 'politics'),print(



]


test_terms = [
    ('catalonia independence: Huge spain unity rally in barcelona', 'politics'),
    ('democrats are desperate to do something  anything  on gun control', 'politics'),
    ('The latest movements on capitol hill', 'politics'),
    ('what do the british prime minister and george clooney have in common?', 'politics'),
    ('Ken Starr on Russia: I expect indictments', 'politics'),
    ('Donald Trump is playing zero-dimensional chess', 'politics'),
    ('Trump touts Tillerson, Kelly, comments on Weinstein on way to fundraiser', 'politics'),
    ('trump to attend NATO meeting in May, White House says','politics'),
    ('milky way is our own galaxy', 'sci'),
    ('best mma fighter', 'sport' ),
('working capital', 'business'),
    ('microwave anisotropy probe','sci'),
    ('voyager satellite', 'sci'),
    ('infrared astronomical satellite iras', 'sci'),
    ('strategic marketing management', 'business'),
    ('strategic marketing management', 'business'),
    ('stock market', 'business'),
    ('stock turnover', 'business'),
    ('small business investment council (sbic)', 'business'),
    ('skimming pricing strategy', 'business'),
    ('selective distribution', 'business'),
    ('selling approaches', 'business'),
    ('seed capital', 'business'),
    ('sales on credit', 'business'),
    ('sales break even', 'business'),
    ('return on sales', 'business'),
    ('return visitors', 'business'),
    ('return on assets', 'business'),
    ('return on investment', 'business'),
    ('relevant cost', 'business'),
    ('receivables turnover', 'business'),
    ('regional marketing', 'business'),
    ('questionable costs', 'business'),
    ('proprietary  limited company', 'business'),
    ('profit before interest and taxes', 'business'),
    ('profit or loss', 'business'),
    ('product line pricing', 'business'),
    ('product development strategy', 'business'),
    ('product life cycle', 'business'),
    ('product development', 'business'),
    ('product definition', 'business'),
    ('pro forma income statement', 'business'),
    ('price elasticity of demand', 'business'),
    ('point of purchase advertising', 'business'),
    ('plant and equipment', 'business'),
    ('personal selling', 'business'),
    ('penetration pricing strategy', 'business'),
    ('payroll burden', 'business'),
    ('payment delay', 'business'),
    ('payment days', 'business'),
    ('paid in capital', 'business'),
    ('original equipment manufacturer', 'business'),
    ('opportunity cost', 'business'),
    ('operating leverage', 'business'),
    ('operating expenses', 'business'),
    ('offering mix or portfolio', 'business'),
    ('obligations incurred', 'business'),
    ('not invented here', 'business'),
    ('new brand strategy', 'business'),
    ('company net worth', 'business'),
    ('net profit', 'business'),
    ('net profit margin before taxes', 'business'),
    ('net present value', 'business'),
    ('net cash flow', 'business'),
    ('multiple channel system', 'business'),
    ('moving weighted average', 'business'),
    ('materials included in cost of sales', 'business'),
    ('market development funds', 'business'),
    ('market development strategy', 'business'),
    ('market evolution', 'business'),
    ('market penetration strategy', 'business'),
    ('market plan', 'business'),
    ('market redefinition', 'business'),
    ('market sales potential', 'business'),
    ('market segmentation', 'business'),
    ('market share', 'business'),
    ('market development strategy', 'business'),
    ('market penetration strategy', 'business'),
    ('marketing audit', 'business'),
    ('marketing cost analysis', 'business'),
    ('marketing mix', 'business'),
    ('marketing plan', 'business'),
    ('long-term liabilities', 'business'),
    ('long-term assets', 'business'),
    ('long-term interest rate', 'business'),
    ('limited liability partnership', 'business'),
    ('limited (public) company (aus)', 'business'),
    ('limited liability company', 'business'),
    ('leveraged buy out', 'business'),
    ('inventory turnover', 'business'),
    ('inventory turns', 'business'),
    ('interest expense', 'business'),
    ('intensive distribution', 'business'),
    ('intergrated marketing communications', 'business'),
    ('innovation: evolutionary or revolutionary', 'business'),
    ('initial public offering', 'business'),
    ('income statement', 'business'),
    ('guerrilla marketing concept', 'business'),
    ('guerrilla marketing investment strategy', 'business'),
    ('guerrilla marketing', 'business'),
    ('gross margin', 'business'),
    ('gross margin percent', 'business'),
    ('full-cost price strategies', 'business'),
    ('future value projections', 'business'),
    ('front end', 'business'),
    ('frequency marketing', 'business'),
    ('forms of market research', 'business'),
    ('floating liabilities', 'business'),
    ('fixed liabilities', 'business'),
    ('fixed cost', 'business'),
    ('fiscal year', 'business'),
    ('first mover disadvantage', 'business'),
    ('fighting brand strategy', 'business'),
    ('features, advantages, and benifits', 'business'),
    ('exclusive distribution', 'business'),
    ('everett rogers', 'business'),
    ('equity financing', 'business'),
    ('evaluating ideas and opportunities', 'business'),
    ('economies of scale', 'business'),
    ('effective demand', 'business'),
    ('effective tax rate', 'business'),
    ('entrepreneur in heat', 'business'),
    ('direct mail marketing', 'business'),
    ('direct marketing', 'business'),
    ('earnings before interest and taxes', 'business'),
    ('earnings before interest taxes depreciation and amortization', 'business'),
    ('neutron star', 'sci'),
    ('next generation space telescope ngst mission', 'sci'),
    ('proton rocket', 'sci'),
    ("ion is a atom", "sci"),
    ("Kenya's Keitany relishes return to New York to defend marathon title","sport"),
    ("Mayweter won by tko in 9 round ", "sport"),
    ('muhammad ali was southpaw strike left hand', "sport"),
    ('boxer made good counterpunch', "sport"),
    ("figther is into ropes", 'sport'),
    ('blow under the belt', 'sport'),
    ("referee made spit decision", "sport"),
    ('match was ten rounds', 'sport'),
    ('jupiter is giant gas ball', 'sci'),
    ("fighters move into  ring",'sport'),
    ("team needs defender", 'sport'),
    ('mlb season begin soon', 'sport'),
    ('two minutes penalty for hooking ', 'sport'),
    ("gloves are heavy", 'sport'),
    ("need net to play this game", 'sport'),
    ('hearn wants to promote carl frampton ', 'sport'),
    ("pitch was dry and exelent", 'sport'),
    ("player makes foul",'sport'),
    ("point", "sport"),
    ("all time points leaders", "sport"),
    ("latest Formula 1 racing information and content ", "sport"),
    ("barcelona wins champions league", 'sport'),
    ("clubs", 'sport'),
    ("premier league starts next week", 'sport'),
    ("formula", 'sport'),
    ('rally is motorsport ', "sport"),
    ('motorsport', 'sport'),
    ('kontinen wins us  open', "sport"),
    (' world cup next summer ', 'sport'),
    (' jokerit has new coach', 'sport'),
    ('rask is best goalie', 'sport'),
    #('goalies', 'sport'),
    ("ufc is combat sport", 'sport'),
    ('poker card game ', 'sport'),
    ('short set is played to four games instead of six', 'sport'),
    ('transfers', 'sport'),
    ("bolt makes new record", 'sport'),
    ("Dow Jones industrial average", "business"),
    ("gold price is up ", "business"),
    ("hostile takeover", "business"),
    ("inflation", "business"),
    ("invisible hand", "business"),
    ("earnings per share", "business"),
    ("EPS", "business"),
    ("Economic growth", "business"),
    ("economies of scale", "business"),
    ("elasticity", "business"),
    ("endowment policy", "business"),
    ("enterprise value", "business"),
    ("Equity", "business"),
    ("equity derivatives", "business"),
    ("ethical investment", "business"),
    ("european bank for reconstruction and development", "business"),
    ("european central bank", "business"),
    ("externalities", "business"),
    ("puck", "sport"),
    (" national hockey league", "sport"),
    ("soccer is football ", "sport"),
    ("team", "sport"),
    ("ski", "sport"),
    ("skiing", "sport"),
    ("competition", "sport"),
    ("derby", "sport"),
    ("racing", "sport"),
    ("nhl", "sport"),
    ("NHL", "sport"),
    ("khl is russian hockey league ", "sport"),
    ("basketball season starting ", 'sport'),
    ('golf', "sport"),
    ("match least 10 round", "sport"),
    ("beat", "sport"),
    ("trump", 'politics'),
    ("Trump",  "politics"),
    ('Obama', "politics"),
    ("president trump", "politics"),
    ("mr Trump", "politics"),
    ("Trump's trip", "politics"),
    ("putin", "politics"),
    ("minister", "politics"),
    ("dark horse", "politics"),
    ("delegate", "politics"),
    ("demagogue" , "politics"),
    ("fence mending", "politics"),
    ("filibuster", "politics"),
    ("fishing expedition", "politics"),
    ("front burner", "politics"),
    ("gerrymander", "politics"),
    ("GOP", "politics"),
    ("grass roots","politics"),
    ("ideology", "politics"),
    ("incumbent", "politics"),
    ("inside the beltway", "politics"),
    ("lame duc", "politics"),
    ("left-wing", "politics"),
    ("lobby" , "politics"),
    ("machine politics", "politics"),
    ("mccarthyism" , "politics"),
    ("muckraker", "politics"),
    ("nomination", "politics"),
    ("nominee", "politics"),
    ("photo-op", "politics"),
    ("platform", "politics"),
    ("debate", "politics"),
    ("vote", "politics"),
    ("political party", "politics"),
    ("political suicide", "politics"),
    ("poll", "politics"),
    ("pork barrel",  "politics"),
    ("primary", "politics"),
    ("pundit",  "politics"),
    ("reactionary", "politics"),
    ("red tape", "politics"),
    ("rubber chicken circuit", "politics"),
     ("silent majority", "politics"),
     ("slate", "politics"),
     ("smoke-filled room", "politics"),
     ("spin", "politics"),
     ("stump", "politics"),
     ("swing vote", "politics"),
     ("trial balloon", "politics"),
     ("whip", "politics"),
     ("whistle-stopping", "politics"),
     ("witch hunt", "politics"),
     ("king is leader ", "politics"),
     ("president is head of state", "politics"),
     ("minister has power", "politics"),
     ("feminism is woman", "politics"),
     ("flag symbol of country", "politics"),
     (" finland is land", "politics"),
    ("scientific advice politics european way", "sci"),
    ('argon is a chemical element with symbol ar', 'sci'),
    ("cassini hints at young age for saturn's rings", 'sci'),
    ("errol spence to fight in december or january", 'sport'),
    (" countdown to canelo vs. golovkin", 'sport'),
    ("joshua wants deontay wilder vs. luis ortiz winner", 'sport'),
    ("bulls knew cameron bayne Couldn't play In nba after 2nd practice", 'sport'),
    ("i voted trump 2017", 'politics'),
    ("baseball is american national game", "sport"),
    ("mars red planet", 'sci'),
    ('earth will be hit by an asteroid','sci'),
    ("wow signal found in space", 'sci'),
    ("patric laine has best shot", 'sport'),
    ("that goal was offside", 'sport'),
    ('that jab and hook lands', 'sport'),
    ("boxer wears globs", 'sport'),
    ("QB Brock Osweiler released by Browns tells espn", "sport"),
    ("nfl players who protested during the national anthem this preseason","sport"),
    ("paavo nurmi was great runner", 'sport'),
    ("carl lewis won 10 olympic golds", 'sport'),
    ("you play in cord", "sport"),
    ("that was birde put", 'sport'),
    ("i play golf", 'sport'),
    ("skiing is winter sport", 'sport'),
    ("Pele was best soccer player", 'sport'),
    ("Murinhno is manager", "sport"),

    #('all acute lymphoblastic leukemia', 'medical'),
    #('ami acute myocardial infarction heart attack', 'medical'),
   # ('ball bcell acute lymphoblastic leukemia', 'medical'),
   # ('fsh follicle stimulating hormone a blood test for follicle stimulating hormone which is used to evaluate fertility in women', 'medical'),
  #  ('hape high altitude pulmonary edema', 'medical'),
 #   ('hps hantavirus pulmonary syndrome a type of contagious infectious disease transmitted by rats infected with the virus', 'medical'),    ('ibs irritable bowel syndrome a medical disease that involves the gastrointestinal tract', 'medical'), ('iddm insulindependent diabetes mellitus type 1 diabetes', 'medical'), ('mds myelo dysplastic syndrome', 'medical'), ('nbccs nevoid basal cell carcinoma syndrome', 'medical'), ('pe pulmonary embolism a type of blood clot in the lungs', 'medical'), ('sids sudden infant death syndrome', 'medical'), ('tsh thyroid stimulating hormone a blood test for tsh is used to diagnose thyroid disease', 'medical'), ('ac before meals as in taking a medicine before meals', 'medical'), ('ag ratio albumin to globulin ratio', 'medical'), ('acl anterior cruciate ligament acl injuries are one of the most common ligament injuries to the knee the acl can be sprained or completely torn from trauma andor degeneration', 'medical'), ('ad lib at liberty for example a patient may be permitted to move out of bed freely and orders would therefore be for activities to be ad lib', 'medical'), ('afr acute renal failure', 'medical'), ('adhd attention deficit hyperactivity disorder', 'medical'), ('adr adverse drug reaction if a patient is taking a prescription drug to treat high blood pressure disease', 'medical'), ('aids acquired immune deficiency syndrome', 'medical'), ('aka above the knee amputation', 'medical'), ('anuric not producing urine a person who is anuric is often critical and may require dialysis', 'medical'), ('aned alive no evidence of disease the patient arrived in the er alive with no evidence of disease', 'medical'), ('adh antidiuretic hormone', 'medical'), ('ards acute respiratory distress syndrome', 'medical'), ('arf acute renal kidney failure', 'medical'), ('ascvd atherosclerotic cardiovascular disease a form of heart disease', 'medical'), ('bid twice daily as in taking a medicine twice daily', 'medical'), ('bld blood blood was visible on the patient’s scalp', 'medical'), ('bandemia slang for elevated level of band forms of white blood cells', 'medical'), ('bibasilar at the bases of both lungs for example someone with a pneumonia in both lungs might have abnormal bibasilar breath sounds', 'medical'), ('bka below the knee amputation', 'medical'), ('bmp basic metabolic panel electrolytes potassium sodium carbon dioxide and chloride and creatinine and glucose', 'medical'), ('bp blood pressure blood pressure is recorded as part of the physical examination it is one of the vital signs', 'medical'), ('bpd borderline personality disorder a personality disorder', 'medical'), ('bso bilateral salpingooophorectomy a bso is the removal of both of the ovaries and adjacent fallopian tubes and often is performed as part of a total abdominal hysterectomy', 'medical'), ('cs culture and sensitivity performed to detect infection', 'medical'), ('co complaint of the patients expressed concern', 'medical'), ('cap capsule', 'medical'), ('ca cancer carcinoma for example a patient who undergoing treatment for cancer should assure that they are eating and drinking enough fluids daily both during and after treatment', 'medical'), ('cabg coronary artery bypass graft a surgery involving the heart', 'medical'), ('cbc complete blood count', 'medical'), ('cc chief complaint the patients main concern', 'medical'), ('cde complete dental oral evaluation', 'medical'), ('cc cubic centimeters for example the amount of fluid removed from the body is recorded in ccs', 'medical'), ('chem panel chemistry panel a comprehensive screening blood test that indicates the status of the liver kidneys and electrolytes', 'medical'), ('cpap continuous positive airway pressure a treatment for sleep apnea', 'medical'), ('copd chronic obstructive pulmonary disease', 'medical'), ('ct chemotherapy a type of treatment therapy for cancer', 'medical'), ('cva cerebrovascular accident stroke', 'medical'), ('dc or dc discontinue or discharge for example a doctor will dc a drug alternatively the doctor might dc a patient from the hospital', 'medical'), ('dcis ductal carcinoma in situ a type of breast cancer the patient is receiving treatment for ductal carcinoma in situ', 'medical'), ('ddx differential diagnosis a variety diagnostic possibilities are being considered to diagnose the type of cancer present in the patient', 'medical'), ('djd degenerative joint disease another term for osteoarthritis', 'medical'), ('dm diabetes mellitus', 'medical'), ('dnc dc or d and c dilation and curettage widening the cervix and scrapping with a curette for the purpose of removing tissue lining the inner surface of the womb uterus', 'medical'), ('dnr do not resuscitate this is a specific order not to revive a patient artificially if they succumb to illness if a patient is given a dnr order they are not resuscitated if they are near death and no code blue is called', 'medical'), ('doe dyspnea on exertion shortness of breath with activity', 'medical'), ('dtr deep tendon reflexes these are reflexes that the doctor tests by banging on the tendons with a rubber hammer', 'medical'), ('dvt deep venous thrombosis blood clot in large vein', 'medical'), ('etoh alcohol etoh intake history is often recorded as part of a patient history', 'medical'), ('ect electroconclusive therapy a procedure used to control seizures convulsions', 'medical'), ('fx fracture', 'medical'), ('g gram a unit of weight the cream is available in both 30 and 60 gram tubes', 'medical'), ('gomer slang for get out of my emergency room', 'medical'), ('gvhd graft vs host disease it is complicated by the syndromes of acute and chronic graftvshost disease gvhd', 'medical'), ('gtt drops', 'medical'), ('hh hemoglobin and hematocrit when the h  h is low anemia is present the hh can be elevated in persons who have lung disease from long term smoking or from disease such as polycythemia rubra vera', 'medical'), ('hp history and physical examination', 'medical'), ('hs at bedtime as in taking a medicine at bedtime', 'medical'), ('ho or ho history of a past event that occurred', 'medical'), ('ha headache', 'medical'), ('hrt hormone replacement or hormone replacement therapy', 'medical'), ('htn hypertension', 'medical'), ('id incision and drainage', 'medical'), ('ibd inflammatory bowel disease a name for two disorders of the gastrointestinal bi tract crohn’s disease and ulcerative colitis', 'medical'), ('icd implantable cardioverter defibrillator', 'medical'), ('icu intensive care unit the patient was moved to the intensive care unit', 'medical'), ('im intramuscular this is a typical notation when noting or ordering an injection shot given into muscle such as with b12 for pernicious anemia', 'medical'), ('imp impression this is the summary conclusion of the patients condition by the healthcare professional at that particular date and time', 'medical'), ('itu intensive therapy unit', 'medical'), ('in vitro in the laboratory', 'medical'), ('in vivo in the body', 'medical'), ('ipf idiopathic pulmonary fibrosis a type of lung disease', 'medical'), ('iu international units', 'medical'), ('jt joint', 'medical'), ('k potassium an essential electrolyte frequently monitored regularly in intensive care', 'medical'), ('kcl potassium chloride', 'medical'), ('lcis lobular carcinoma in situ a type of cancer of the breast the patient is receiving treatment for lobular carcinoma in situ', 'medical'), ('lbp low back pain lbp is one of most common medical complaints', 'medical'), ('llq left lower quadrant diverticulitis pain is often in the llq of the abdomen', 'medical'), ('luq left upper quadrant the spleen is located in the luq of the abdomen', 'medical'), ('lytes electrolytes potassium sodium carbon dioxide and chloride', 'medical'), ('mcl medial collateral ligament', 'medical'), ('mg milligrams', 'medical'), ('mh medical history', 'medical'), ('ml milliliters', 'medical'), ('mvp mitral valve prolapse', 'medical'), ('nv nausea or vomiting', 'medical'), ('na sodium an essential electrolyte frequently monitored regularly in intensive care', 'medical'), ('ncp nursing care plan', 'medical'), ('npo nothing by mouth for example if a patient was about to undergo a surgical operation requiring general anesthesia they may be required to avoid food or beverage prior to the procedure', 'medical'), ('nsr normal sinus rhythm of the heart', 'medical'), ('op ova and parasites stool o  p is tested in the laboratory to detect parasitic infection in persons with chronic diarrhea', 'medical'), ('od right eye', 'medical'), ('os left eye', 'medical'), ('ou both eyes', 'medical'), ('orif open reduction and internal fixation such as with the orthopedic repair of a hip fracture', 'medical'), ('p pulse pulse is recorded as part of the physical examination it is one of the vital signs', 'medical'), ('p¯ after meals as in take two tablets after meals', 'medical'), ('po by mouth from the latin terminology per os', 'medical'), ('prn as needed so that it is not always done but done only when the situation calls for it or example taking a pain medication only when having pain and not without pain', 'medical'), ('pcl posterior cruciate ligament', 'medical'), ('pd progressive disease patients at risk of developing progressive disease of the kidneys include those with proteinuria or hematuria', 'medical'), ('perrla pupils equal round and reactive to light and accommodation', 'medical'), ('pft pulmonary function test a test to evaluate the how well the lungs are functioning', 'medical'), ('perrla pupils equal round and reactive to light and accommodation', 'medical'), ('plt platelets one of the blood forming elements along with the white and red blood cells', 'medical'), ('pmi point of maximum impulse of the heart when felt during examination as in beats against the chest', 'medical'), ('pms premenstrual syndrome', 'medical'), ('pt physical therapy', 'medical'), ('pth parathyroid hormone', 'medical'), ('ptsd posttraumatic stress syndrome', 'medical'), ('pud peptic ulcer disease a type of ulcer of the stomach', 'medical'), ('qd each day as in taking a medicine daily', 'medical'), ('qid four times daily as in taking a medicine four times daily', 'medical'), ('q2h every 2 hours as in taking a medicine every 2 hours', 'medical'), ('q3h every 3 hours as in taking a medicine every 3 hours', 'medical'), ('qam each morning as in taking a medicine each morning', 'medical'), ('qhs at each bedtime as in taking a medicine each bedtime', 'medical'), ('qod every other day as in taking a medicine every other day', 'medical'), ('qpm each evening as in taking a medicine each evening', 'medical'), ('ra rheumatoid arthritis a type of joint disease', 'medical'), ('rds respiratory distress syndrome', 'medical'), ('ro rule out doctors frequently will rule out various possible diagnoses when figuring out the correct diagnosis', 'medical'), ('reb rebound as in rebound tenderness of the abdomen when pushed in and then released', 'medical'), ('rlq right lower quadrant the appendix is located in the rlq of the abdomen', 'medical'), ('ros review of systems an overall review concerns relating to the organ systems such as the respiratory cardiovascular and neurologic systems', 'medical'), ('ruq right upper quadrant the liver is located in the ruq of the abdomen', 'medical'), ('sp status post for example a person who had a knee operation would be sp a knee operation', 'medical'), ('sad season affective disorder a type of depression that occurs during the winter months when there is little light', 'medical'), ('sob shortness of breath', 'medical'), ('sq subcutaneous this is a typical notation when noting or ordering an injection shot given into the fatty tissue under the skin such as with insulin for diabetes mellitus', 'medical'), ('t temperature temperature is recorded as part of the physical examination it is one of the vital signs', 'medical'), ('ta tonsillectomy and adenoidectomy', 'medical'), ('tid three times daily as in taking a medicine three times daily', 'medical'), ('tab tablet', 'medical'), ('tah total abdominal hysterectomy', 'medical'), ('tah total abdominal hysterectomy a type of surgery to remove a woman’s uterus fallopian tubes and ovaries', 'medical'), ('thr total hip replacement', 'medical'), ('tkr total knee replacement', 'medical'), ('tmj tempomandibular joint', 'medical'), ('ua or ua urinalysis a ua is a typical part of a comprehensive physical examination', 'medical'), ('u or u unit mistaken as the number 0 or 4 causing a 10fold overdose or greater for example 4u seen as 40 or 4u seen as 44 mistaken as cc so the dose is given in volume instead of units for example 4u seen as 4cc', 'medical'), ('uln upper limits of normal', 'medical'), ('uri upper respiratory infection such as sinusitis or the common cold', 'medical'), ('ut dict as directed as in taking a medicine according to the instructions that the health care professional gave in the office or in the past', 'medical'), ('uti urinary tract infection', 'medical'), ('vss vital signs are stable this notation means that from the standpoint of the temperature blood pressure and pulse the patient is doing well', 'medical'), ('wt weight body weight is often recorded as part of the physical examination', 'medical'), ('xrt radiotherapy external a type of treatment that uses radiation', 'medical')
]
